### ISSUE TITLE
People search on homepage

### ISSUE THREAD

**Issue by kwaychoff** [HCDigitalScholarship/LinkedFlask#6]
Some of the changes I made on 10/21 have made it so if you search an exact name under people it gives the letters page for that person.

I think it might be a problem with my if statements in the "home" function in hello.py.

**Comment by kwaychoff** [comment]
I am not sure that I can fix this problem without some other method of being able to tell which form is being filled in/submitted

**Comment by kwaychoff** [comment]
http://stackoverflow.com/questions/18290142/multiple-forms-in-a-single-page-using-flask-and-wtforms

Someone had a similar problem.

**Comment by mfhodges** [comment]
The core of the problem is that even though letterforms isnt filled out it is claiming that .validate() is true.

**Comment by kwaychoff** [comment]
I think I solved this by giving the forms a name in home.html.
